version: '3.8'

services:
  banco:
    image: postgres:16-alpine
    container_name: pg-compose
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - dados-pg-compose:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-compose
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - banco

volumes:
  dados-pg-compose:
